name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run notebook tests
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute notebooks/sentiment_test.ipynb --output test_output.ipynb
      - name: Check Python code style
        run: |
          pip install flake8
          flake8 scripts/ --max-line-length=120
